# Generated by Django 4.1.5 on 2023-01-25 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('surname', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('phoneNumber', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('afertaSubmission', models.BooleanField(verbose_name='Согласие с афертой')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=512, verbose_name='Описание')),
                ('pricePerHour', models.IntegerField(verbose_name='Цена за час')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('readyToRent', models.CharField(choices=[('ON', 'Готов к аренде'), ('OFF', 'News')], default='OFF', max_length=3, verbose_name='Статус')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.appuser', verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderState', models.CharField(choices=[('ON', 'Арендуется'), ('OFF', 'Не арендуется')], default='OFF', max_length=3, verbose_name='Статус аренды')),
                ('arendator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.appuser', verbose_name='Арендатор')),
                ('parkingPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.parkingplace', verbose_name='Машино-место')),
            ],
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец карты')),
            ],
        ),
    ]
