# Generated by Django 4.1.5 on 2023-02-01 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='bankcard',
            options={'verbose_name': 'Банковская карта', 'verbose_name_plural': 'Банковские карты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
        migrations.AlterModelOptions(
            name='parkingplace',
            options={'verbose_name': 'Машино-место', 'verbose_name_plural': 'Машино-места'},
        ),
        migrations.AlterField(
            model_name='appuser',
            name='afertaSubmission',
            field=models.BooleanField(default=True, verbose_name='Согласие с афертой'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='balance',
            field=models.IntegerField(default=1000, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.appuser', verbose_name='Владелец карты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderState',
            field=models.CharField(choices=[('ON', 'Арендуется'), ('OFF', 'Аренда завершена')], default='ON', max_length=3, verbose_name='Статус аренды'),
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='readyToRent',
            field=models.CharField(choices=[('ON', 'Готов к аренде'), ('OFF', 'Не готов к аренде')], default='OFF', max_length=3, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Сheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=333, verbose_name='Стоимость парковки')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Сheque_beneficiary', to='baseapp.appuser', verbose_name='Владелец карты')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Сheque_payer', to='baseapp.appuser', verbose_name='Плательщик')),
            ],
        ),
    ]
