# Generated by Django 4.1.5 on 2023-02-02 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_alter_appuser_options_alter_bankcard_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сheque',
            options={'verbose_name': 'Банковский чек', 'verbose_name_plural': 'Банковские чеки'},
        ),
        migrations.AddField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='сheque',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='readyToRent',
            field=models.CharField(choices=[('ON', 'Готов к аренде'), ('OFF', 'Не готов к аренде')], default='ON', max_length=3, verbose_name='Статус'),
        ),
    ]
