# Generated by Django 4.1.7 on 2023-02-19 22:47

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_remove_parkingplace_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingplace',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326),
        ),
    ]
