# Generated by Django 4.1.7 on 2023-03-09 16:54

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_parkingplace_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='name',
            field=models.CharField(help_text='Введите ваше имя', max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(37.618423, 55.751244), srid=4326),
        ),
    ]
